### ISSUE TITLE
Entry location and seasonality

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#77]
## Description

Add location and seasonality to entry details:

![image](https://user-images.githubusercontent.com/4369024/114255229-aef02b80-9979-11eb-97e2-f801dac5a04b.png)

Full entry details page for context:

![image](https://user-images.githubusercontent.com/4369024/114255233-b4e60c80-9979-11eb-82e3-d68823a361e0.png)

Closes #47 

## Todo

- Reverse geocode latitude and longitude of location to produce a street
  - Don't do this logic in the actual component, import a helper function to do this
  - You prob want to move search/locationInfo.js to general utils, and add your helper function there
- Convert season_start and season_end, if no_season is true, to month names
  - Same here: the EntryDetails component is already on the large side
  - Maybe move ACCESS_TYPE, formatISOString, formatSeasonality to entry/textFormatters.js
- Consider creating a separate component (kind of like ResourceList) for the location and seasonality
- Clicking on the location (the address or the icon) should center the map view on the lat and lng of the location itself
![image](https://user-images.githubusercontent.com/4369024/114255860-b4e70c00-997b-11eb-98b1-635bf45b35b4.png)
  - After clicking on the address, a pin should appear over the location:
  ![image](https://user-images.githubusercontent.com/4369024/114255794-4609b300-997b-11eb-9971-2220790d6a5b.png)
  - Push /map on desktop too
  - You can do this by adding a field in SearchContext called selectedLocation), passing that to Map
  - So EntryDetails needs to set selectedLocation with the entire location object
  - MapPage has a new useEffect on selectedLocation that's pretty similar to the one on searchViewport, except it does `setView(fitContainerBounds(getGeolocationBounds({ bounds of the location })`
  - Map adds a boolean prop called selected to `<Location>` if `location.id === selectedLocation`
  - Style Location.js to support having a pin over it, if selected is true

**Comment by code-arman** [comment]
1) Create a ResetButton that basically resets the button to look like no border, no padding, font-family: inherit, color: inherit, cursor: pointer, background: none
     - Look online to see if there's anything he missed

2) Search throughout the project for anything that does this. This is usually iconButton, styled button, Button.js, styled.button change it to styled(ResetButton) and remove the relevant styles

3) Part three is grab the currently selected entry in search viewport. You know how the browser says /3383. The way you figure out which location to put the pin over is by getting it from the URL. Getting 3383 from the URL. You can use useParams to do this.

**Comment by ezwelty** [comment]
A couple thoughts about this.

1. Reverse geocoding client-side every time a location is displayed will be expensive – on bandwidth and $. Google charges $0.005 per request, so at say 1000 requests per day, that is $150 per month, which our Google grant can absorb for now, but that will need to be kept in check. We currently reverse geocode new locations in the background, but sadly only save city, state, and country (for use at fallingfruit.org/changes). I could start saving the complete formatted address in `Location.address`, which is already returned by the API, to cache the reverse geocoding result and minimize the need to do it client-side if already available.

2. Displaying an address could confuse users, since most locations are on the street or other public location and thus do not have a strict street address. Many reverse geocoding results may be quite vague (e.g. just a city name, or a street number range). But I think we should display whatever address we have for now and see how the users take to it. Perhaps `latitude, longitude` should be shown besides the map icon, and the address below it when available, to communicate that the address is secondary?
